services:
  timelimiter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"  
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/timelimiter?sslmode=disable
      - PORT=3030
      - BACKENDS=http://backend1:80,http://backend2:80,http://backend3:80
    depends_on:
      postgres:
        condition: service_healthy
      backend1:
        condition: service_started
      backend2:
        condition: service_started
      backend3:
        condition: service_started
    restart: no

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timelimiter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend1:
    image: strm/helloworld-http
    ports:
      - "8081:80" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend2:
    image: strm/helloworld-http
    ports:
      - "8082:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend3:
    image: strm/helloworld-http
    ports:
      - "8083:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:

networks:
  lb-network: